spring:
  application:
    name: motor-de-regras
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
rabbitmq:
  exchanges:
    motor-de-regras:
      analise:
        concluida: motor-de-regras.analise-concluida.ex
  queue:
    motor-de-regras:
      analise:
        pendente: motor-de-regras.analise-pendente
        concluida: motor-de-regras.analise-concluida
#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
